name: Docs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - run: pip install poetry==1.1.4
    - run: poetry install --extras=docs
    - run: cd docs && poetry run make html