name: Linter
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Acquire sources
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v4
    - name: Install library
      run: poetry install
    - name: Run lint on code
      run: poetry run flake8 wetterdienst example tests
