name: Terraform

permissions:
  contents: read
  id-token: write

on:
  workflow_run:
    workflows: [ "Release Docker Standard" ]

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Google Auth
        uses: google-github-actions/auth@v2
        env:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        with:
          workload_identity_provider: ${{ env.workload_identity_provider }}
          service_account: cicd-dev@wetterdienst.iam.gserviceaccount.com

      - name: Configure docker
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform plan
        working-directory: ./terraform
        run: terraform plan

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve